name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.9 [CE|EE|ECE 2.4.0-2.4.7] 17 Aug 2024
          tag_name: 1.5.9
          body: |2-
            ### softcommerce/module-core [1.5.2]
            - **Fix**: Applied a fix to \SoftCommerce\Core\Model\Store\WebsiteStorage::getStoreIdToWebsiteId method where argument data type for $storeId was changed from string to an integer [#10].

            ### softcommerce/module-plenty-attribute [1.4.0]
            - **Feature**: Introduce new functionality to manage manufacture synchronisation [#5]

            ### softcommerce/module-plenty-attribute-rest-api [1.2.7]
            - **Compatibility**: Compatibility with new functionality introduced in `SoftCommerce_PlentyAttribute` [#1]

            ### softcommerce/module-plenty-category-profile [1.3.11]
            - **Compatibility**: Introduce support for Magento 2.4.7 [#8]

            ### softcommerce/module-plenty-item [1.4.6]
            - **Compatibility**: Introduce support for Magento 2.4.7 [#9]

            ### softcommerce/module-plenty-item-profile [1.7.6]
            - **Compatibility**: Compatibility with new functionality introduced in `SoftCommerce_PlentyAttribute` [#34]
            - **Compatibility**: Introduce support for Magento 2.4.7 [#33]

            ### softcommerce/module-profile-config [1.2.12]
            - **Compatibility**: Introduce support for Magento 2.4.7 [#4]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
