name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.1 [CE|EE|ECE 2.4.0-2.4.7] 17 Sep 2024
          tag_name: 1.6.1
          body: |2-
            ### softcommerce/module-plenty-client [1.4.1]
            - **Enhancement**: Applied changes to allow installation of media channels dynamically opposed to static declaration of image types during install

            ### softcommerce/module-plenty-item-profile [1.8.1]
            - **Enhancement**: Applied changes to allow import of media channels dynamically opposed to static declaration of image types
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
