name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.10 [CE|EE|ECE 2.4.0-2.4.7] 17 Oct 2024
          tag_name: 1.6.10
          body: |2-
            ### softcommerce/module-plenty-client-rest-api [1.3.1]
            - **Fix**: SoftCommerce\PlentyClientRestApi\Model\Response\ConfigDataBuilder::buildItemArrayResponse(): Argument #1 ($item) must be of type array, string given #36

            ### softcommerce/module-plenty-stock-profile-schedule [1.2.10]
            - **Fix** CRITICAL: Message has been rejected: Profile ID is not set [#37]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
