name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.5 [CE|EE|ECE 2.4.0-2.4.7] 22 Apr 2024
          tag_name: 1.5.5
          body: "
### softcommerce/module-plenty-category [1.2.9]
- **Compatibility**: Introduced support for PHP 8.3

### softcommerce/module-plenty-client [1.3.2]
- **Feature**: Introduce new method to retrieve client data by locale. [#2]
- **Compatibility**: Introduced support for PHP 8.3

### softcommerce/module-plenty-item [1.4.5]
- **Compatibility**: Introduced support for PHP 8.3
- **Enhancement**: Removed unused etc/config.xml that has no purpose. 

### softcommerce/module-plenty-item-client [1.2.8]
- **Compatibility**: Introduced support for PHP 8.3

### softcommerce/module-plenty-item-profile [1.7.2]
- **Feature**: Add attribute mapping for availability fields [#29]

### softcommerce/module-plenty-stock [1.3.6]
- **Compatibility**: Introduced support for PHP 8.3
- **Enhancement**: Added new methods `getReservedBundle` and `setReservedBundle` to `SoftCommerce\PlentyStock\Api\Data\InventoryInterface`

### softcommerce/module-plenty-stock-client [1.2.7]
- **Compatibility**: Introduced support for PHP 8.3
- **Enhancement**: Added new methods to `SoftCommerce\PlentyStockClient\Api\Data\WarehouseLocationInterface`

### softcommerce/module-plenty-stock-profile [1.5.1]
- **Enhancement**: Include stock calculation for reservation bundle [#16]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
