name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
    paths-ignore:
      - '.github/*'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.4 [CE|EE|ECE 2.4.0-2.4.7] 21 Mar 2024
          tag_name: 1.5.4
          body: |-
            # Mage2PlentyOs [1.5.4] 21 Mar 2024

            ### softcommerce/automatic-workflow-test [1.0.33]
            - **Feature**: New feature test
            - **Fix**: A fix for xxx

            ### softcommerce/module-fakeentitycreator [1.0.7]
            - **Compatibility**: Compatibility with PHP 8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
