name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.7 [CE|EE|ECE 2.4.0-2.4.7] 01 Oct 2024
          tag_name: 1.6.7
          body: |2-
            ### softcommerce/module-plenty-customer-client [1.2.8]
            - **Enhancement**: Minor changes to codebase `SoftCommerce\PlentyCustomerClient\Model\AddressOptionTypeManagement`

            ### softcommerce/module-plenty-item-client [1.2.10]
            - **Enhancement**: Remove `stock_warehouse_dimension, stock_warehouse_location and stock_warehouse_location_details` configs from client data collection process

            ### softcommerce/module-plenty-order-client [1.4.1]
            - **Enhancement**: Remove `stock_warehouse_dimension, stock_warehouse_location and stock_warehouse_location_details` configs from client data collection process

            ### softcommerce/module-plenty-stock [1.3.8]
            - **Fix**: Too few arguments to function SoftCommerce\PlentyStock\Model\GetOrderItemSourceSelection::generateInventoryRequest() 3 passed, exactly 4 [#33]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
