name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.2 [CE|EE|ECE 2.4.0-2.4.7] 08 Nov 2024
          tag_name: 1.6.2
          body: |2-
            ### softcommerce/module-plenty-order-profile [1.7.6]
            - **Enhancement**: Improvements to shipment creation for out of stock items [#39]

            ### softcommerce/module-plenty-stock [1.3.9]
            - **Enhancement**: Improvements to Order Item source selection algorithm [#38]

            ### softcommerce/module-plenty-stock-profile [1.7.1]
            - **Enhancement**: Improvements to Order Item source selection algorithm [#38]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
