name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.2 [CE|EE|ECE 2.4.0-2.4.7] 21 Sep 2024
          tag_name: 1.6.2
          body: |2-
            ### softcommerce/module-core [1.5.4]
            - **Fix**: Cannot use "String" in namespace as it is reserved since PHP 7 [#13]

            ### softcommerce/module-plenty-attribute [1.4.2]
            - **Feature**: Introduce compatibility with `softcommerce/magento-core` module [#17]

            ### softcommerce/module-plenty-category [1.2.11]
            - **Feature**: Introduce compatibility with `softcommerce/magento-core` module [#17]

            ### softcommerce/module-plenty-item-profile [1.8.2]
            - **Feature**: Introduce compatibility with `softcommerce/magento-core` module [#17]

            ### softcommerce/module-plenty-property [1.3.4]
            - **Feature**: Introduce compatibility with `softcommerce/magento-core` module [#17]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
