name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
    paths-ignore:
      - '.github/*'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.3 [CE|EE|ECE 2.4.0-2.4.7] 21 Mar 2024
          tag_name: 1.5.3
          body: |2-
            ### softcommerce/module-core [1.5.0]
            - **Compatibility**: Introduced compatibility with PHP type declaration [#9]
            - **Compatibility**: Introduced support for PHP 8.3 [#8]
            - **Feature**: Implement functionality to support UI form scope data [#7]

            ### softcommerce/module-plenty-category-profile [1.3.10]
            - **Compatibility**: Introduced support for PHP 8.3 [#7]
            - **Enhancement**: Improvements to UI form components for category configuration profile [#6]

            ### softcommerce/module-plenty-customer-profile [1.1.0]
            - **Enhancement**: An option to retrieve a referrer ID by store cope [#9]
            - **Compatibility**: Introduced support for PHP 8.3 [#8]
            - **Enhancement**: Improvements to UI form components for customer profile configuration [#7]

            ### softcommerce/module-plenty-item-profile [1.7.0]
            - **Compatibility**: Introduced support for PHP 8.3 [#27]
            - **Enhancement**: Improvements to UI form components for item profile configuration [#26]

            ### softcommerce/module-plenty-order [1.4.0]
            - **Compatibility**: Introduced support for PHP 8.3 [#7]
            - **Enhancement**: Introduced compatibility with PHP type declaration [#6]

            ### softcommerce/module-plenty-order-profile [1.7.0]
            - **Compatibility**: Introduced support for PHP 8.3 [#35]
            - **Feature**: Introduced support for scoped configuration within profile UI form components [#34]

            ### softcommerce/module-plenty-order-profile-schedule [1.2.12]
            - **Compatibility**: Introduced support for PHP 8.3 [#3]

            ### softcommerce/module-plenty-profile [1.4.0]
            - **Enhancement**: Changes to profile configuration where referrer ID is now retrieved by store scope instead of website [#2]
            - **Compatibility**: Introduced support for PHP 8.3 [#1]

            ### softcommerce/module-plenty-stock-profile [1.5.0]
            - **Feature**: Introduced support for scoped configuration within profile UI form components [#15]
            - **Compatibility**: Introduced support for PHP 8.3 [#14]

            ### softcommerce/module-profile [1.4.0]
            - **Feature**: Introduced functionality to support UI form scoped data [#3]
            - **Compatibility**: Introduced support for PHP 8.3 [#2]

            ### softcommerce/module-profile-config [1.2.11]
            - **Compatibility**: Introduced support for PHP 8.3 [#2]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
