name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.7 [CE|EE|ECE 2.4.0-2.4.7] 16 May 2024
          tag_name: 1.5.7
          body: |2-
            ### softcommerce/module-plenty-item-profile [1.7.4]
            - **Fix**: Deprecated Functionality: Creation of dynamic property SoftCommerce\PlentyItemProfile\...\ItemStorage::$variationIdToItemId is deprecated [#31]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
