name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.4 [CE|EE|ECE 2.4.0-2.4.7] 25 Sep 2024
          tag_name: 1.6.4
          body: |2-
            ### softcommerce/module-plenty-item [1.5.0]
            - **Feature**: Introduce a feature to delete local item storage from admin UI [#23]

            ### softcommerce/module-plenty-item-profile [1.9.0]
            - **Feature**: Introduce a feature to map product SKUs to Item and Variation IDs [#24]
            - **Feature**: Introduce a feature to schedule item collect process from the admin UI [#22]
            - **Fix**: Add a fix for duplicate client images deletion functionality [#18]

            ### softcommerce/module-profile [1.4.2]
            - **Enhancement**: Add an option to include a menu with item that depends on URL and confirmation message for profile actions button [#25]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
