name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.8 [CE|EE|ECE 2.4.0-2.4.7] 09 Oct 2024
          tag_name: 1.6.8
          body: |2-
            ### softcommerce/module-plenty-order-profile [1.7.4]
            - **Enhancement**: Added a functionality to handle cancelled order status synchronisation [#34]

            ### softcommerce/module-plenty-order-profile-schedule [1.2.14]
            - **Enhancement**: Added order cancel event to handle cancelled order status synchronisation [#34]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
