name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.0 [CE|EE|ECE 2.4.0-2.4.7] 13 Sep 2024
          tag_name: 1.6.0
          body: "
### softcommerce/module-core [1.5.3]
- **Enhancement**: Introduce tooltip renderer for UI columns [#12]
- **Enhancement**: Introduce flattening array interface [#11]

### softcommerce/module-plenty-attribute [1.4.1]
- **Enhancement**: Manor changes that include modification to menu titles.

### softcommerce/module-plenty-category [1.2.10]
- **Enhancement**: Manor changes that include modification to menu titles.

### softcommerce/module-plenty-category-profile [1.3.12]
- **Enhancement**: Manor changes that include modification to menu titles.

### softcommerce/module-plenty-client [1.4.0]
- **Feature**: Added a functionality to create referrers for system attributes to be used for multiple channels [#4]

### softcommerce/module-plenty-client-rest-api [1.3.0]
- **Feature**: Added REST API routes for `referrer` [#2]

### softcommerce/module-plenty-customer [1.3.1]
- **Enhancement**: Manor changes that include modification to menu titles.

### softcommerce/module-plenty-customer-client [1.2.7]
- **Compatibility**: Introduced compatibility with client referrer functionality [#2]

### softcommerce/module-plenty-customer-profile [1.1.2]
- **Compatibility**: Introduced compatibility with client referrer functionality [#11]

### softcommerce/module-plenty-item [1.4.7]
- **Enhancement**: Added status argument to SoftCommerce\PlentyItem\Api\ItemExportQueueManagementInterface::addToQueue function [#11]
- **Enhancement**: Manor changes that include modification to menu titles.

### softcommerce/module-plenty-item-profile [1.8.0]
- **Feature**: Introduce support for controlling product image types by using referrer channels [#38]
- **Enhancement**: Add products to export queue when exporting manually from within the product view page. [#37]
- **Enhancement**: Disable export/import action button on product view pages for products not visible in site visibility [#36]
- **Enhancement**: Reduce the size of message data being saved into profile history for item import/export result messages by flattening array values [#35]

### softcommerce/module-plenty-order [1.4.1]
- **Compatibility**: Introduced compatibility with client referrer functionality [#8]
- **Enhancement**: Manor changes that include modification to menu titles.

### softcommerce/module-plenty-order-client [1.4.0]
- **Feature**: Move order referrer interface over to `softcommerce/module-plenty-client` to make it accessible by all modules [#5] 

### softcommerce/module-plenty-order-profile [1.7.2]
- **Compatibility**: Introduced compatibility with client referrer functionality [#41]
- **Fix**: Could not import order. Order: ###, Reason: Payment Gateway is unreachable at the moment. Please use another payment option. [#40]
- **Enhancement**: Manor changes that include modification to menu titles.

### softcommerce/module-plenty-order-profile-schedule [1.2.13]
- **Compatibility**: Introduced compatibility with client referrer functionality [#4]

### softcommerce/module-plenty-order-rest-api [1.3.0]
- **Feature**: Phase out ReferrerInterface in favour of \SoftCommerce\PlentyClientRestApi\Model\ReferrerInterface [#6]

### softcommerce/module-plenty-property [1.3.3]
- **Enhancement**: Manor changes that include modification to menu titles.

### softcommerce/module-plenty-stock-profile [1.6.0]
- **Feature**: Introduce inventory reservation UI listing to enable data manipulation for reservations [#18]
- **Enhancement**: Manor changes that include modification to menu titles."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
