name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.7.0 [CE|EE|ECE 2.4.0-2.4.7] 12 Dec 2024
          tag_name: 1.7.0
          body: |2-
            ### softcommerce/module-plenty-attribute [1.5.0]
            - **Feature**: Add attributes for manufacturer model to facilitate GPSR data for Product Safety Regulation [#40]

            ### softcommerce/module-plenty-attribute-rest-api [1.2.8]
            - **Compatibility**: Added REST API collect functionality for compatability with GH feature: #40 [https://github.com/softcommerceltd/mage2plenty-os/issues/40]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
