name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.4 [CE|EE|ECE 2.4.0-2.4.7] 25 Mar 2024
          tag_name: 1.5.4
          body: |2-
            ### softcommerce/module-plenty-item-profile [1.7.1]
            - **Enhancement**: Added an option to allow/disallow child product name generation based on parent name and attributes [#28]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
