name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.8.1 [CE|EE|ECE 2.4.0-2.4.7] 15 Jan 2025
          tag_name: 1.8.1
          body: |2-
            ### softcommerce/module-plenty-order-profile [1.8.1]
            -- **Fix**: SourceItemRepository::getQtyPhysical(): Argument #2 ($sourceCode) must be of type string, null given, called in /../softcommerce/module-plenty-order-profile/Model/OrderImportService/Generator/Shipment.php on line 247 [#42]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
