name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.8 [CE|EE|ECE 2.4.0-2.4.7] 28 May 2024
          tag_name: 1.5.8
          body: |2-
            ### softcommerce/module-core [1.5.1]
            - **Feature**: Added service & processor interface wrapper for dependant modules that use data processing.

            ### softcommerce/module-plenty-item-profile [1.7.5]
            - **Feature**: Add an option to collect + import items from within the product page view #32

            ### softcommerce/module-profile [1.4.1]
            - **Enhancement**: Preserve an array key for context services in `SoftCommerce\Profile\Model\ServiceAbstract\Service::initServices` [#4]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
