name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.5 [CE|EE|ECE 2.4.0-2.4.7] 27 Sep 2024
          tag_name: 1.6.5
          body: |2-
            ### softcommerce/module-core [1.5.6]
            - **Enhancement**: Added an option to display installed metapackages for the bundled modules

            ### softcommerce/module-plenty-category-profile [1.3.13]
            - **Compatibility**: Applied compatibility for profile common configuration paths [#27]

            ### softcommerce/module-plenty-customer-profile [1.1.3]
            - **Compatibility**: Applied compatibility for profile common configuration paths [#27]

            ### softcommerce/module-plenty-item-profile [1.9.1]
            - **Compatibility**: Applied compatibility for profile common configuration paths [#27]

            ### softcommerce/module-plenty-order-profile [1.7.3]
            - **Enhancement**: Generate unique ID for guest customers that is required for PM contact number [#28]
            - **Compatibility**: Applied compatibility for profile common configuration paths [#27]

            ### softcommerce/module-plenty-profile [1.5.0]
            - **Feature**: Profiles that share common configuration paths can now be saved simultaneously from any profile [#27]

            ### softcommerce/module-plenty-stock [1.3.7]
            - **Enhancement**: Addressed minor performance improvements for `SoftCommerce\PlentyStock\Model\GetOrderItemSourceSelection::generateInventoryRequest()`

            ### softcommerce/module-plenty-stock-profile [1.7.0]
            - **Compatibility**: Applied compatibility for profile common configuration paths [#27]
            - **Feature**: Introduce custom Source Selection Algorithm to achieve precise NET calculation by accounting for reservations [#26]

            ### softcommerce/module-profile [1.4.3]
            - **Enhancement**: Added profile config data to event dispatcher for save before/after events.

            ### softcommerce/module-profile-config [1.2.13]
            - **Fix**: Apply a fix where profile config scope writer saves value as array opposed to serialised data [#29]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
